name: JourneyTest
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  journey-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: Setup tools used by WaaS
        uses: metro-digital/setup-tools-for-waas@v0.x
        with:
          version: 'waas/v2'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build kustomize plugin and install it
        run: |
          export XDG_CONFIG_HOME=${XDG_CONFIG_HOME-${HOME}/.config}
          make build
          make install  
      - name: Authenticate to GCP project
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/809560828278/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: kustomize-gsm-secret-reader@metro-cf-2tier-github-mom.iam.gserviceaccount.com 
      - name: Run journey tests
        run: |
          cd journey-test && ./journey-test.sh
