name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: |
          go mod tidy
          cp LICENSE ./release
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o=./release/KGCPSecret ./main/ 
          tar -C ./release -cvzf ./release/KGCPSecret.linux.amd64.tar.gz ./KGCPSecret ./LICENSE ./LICENSES
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o=./release/KGCPSecret ./main/ 
          tar -C ./release -cvzf ./release/KGCPSecret.darwin.amd64.tar.gz ./KGCPSecret ./LICENSE ./LICENSES
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o=./release/KGCPSecret ./main/ 
          tar -C ./release -cvzf ./release/KGCPSecret.darwin.arm.tar.gz ./KGCPSecret ./LICENSE ./LICENSES
          GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -o=./release/KGCPSecret ./main/ 
          tar -C ./release -cvzf ./release/KGCPSecret.windows.386.tar.gz ./KGCPSecret ./LICENSE ./LICENSES
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm install conventional-changelog-conventionalcommits
        working-directory: ./release
      - run: npx semantic-release@17.4.3
        working-directory: ./release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: metro-digital-bot
          GIT_AUTHOR_EMAIL: info@metro.digital
          GIT_COMMITTER_NAME: metro-digital-bot
          GIT_COMMITTER_EMAIL: info@metro.digital
